### ISSUE TITLE
Repro Install failed

### ISSUE THREAD

**Issue by github-user-1** [robwebset/repository.robwebset#1]
I just tried to install the repro version 1.0.0 but I just got the error message that it failed. I'm running libreelec (Kodi version 16.1) on a Raspberry Pi 2. I uploaded the zip-file and tried install it from the menu as suggested. Any ideas what could be wrong?

**Comment by robwebset** [comment]
Nothing springs to mind - would you be able to enable kodi logging and post a link to the log when you've tried to install it?

Thanks, Rob

**Comment by github-user-1** [comment]
Here you go - the log file I got after a restart and then reproducing the error from the repro install:

http://sprunge.us/LRQO

Please let me know if you need something else. My setup (Raspberry Pi2 with LibreElec should be rather simple, i.e. not much changed from the standard).

**Comment by robwebset** [comment]
Thanks for the log file, looking at the log it appears that the zip file is damaged:

> 11:26:50  91.456230 T:1962872832   DEBUG: CAddonInstaller: installing from zip '/storage/downloads/repository.robwebset-1.0.0.zip'
> 11:26:50  91.465004 T:1962872832   DEBUG: ZipManager: not a zip file!

Please can you try downloading again and see if that fixes it:

https://github.com/robwebset/repository.robwebset/raw/master/repos/repository.robwebset/repository.robwebset-1.0.0.zip

Thanks
Rob

**Comment by github-user-1** [comment]
It worked - great and many thanks! I have honestly now idea what is different this time but at least it is installed now :-)

Screenshot:
![clipboard02](https://cloud.githubusercontent.com/assets/6796538/20641067/76ec9cf4-b3e7-11e6-8a40-91893c4a83ff.png)
